### ISSUE TITLE
Investigate Mikhail's DX issue (Grid)

### ISSUE THREAD

**Issue by czp13** [vaadin/form-filler-addon#45] opened 2023-08-11 17:27 UTC
Check Mikhail's branch and understand, and provide a fix why his custom grid implementation did not work.

**Comment by mgarciavaadin** [comment] 2023-08-13 13:33
So the problem is that the bean has not an empty public constructor. The [https://github.com/vaadin/form-filler-addon/tree/dx-test-mikhail](test) has been updated and now works. 

PR #56 is in short term dealing with the issue adding a detailed error message to warn the user. Anyways Issue #57 remember to do further research to try to fix the situation if possible. 

@czp13 check if we could close this issue then (I think we can as the cause is tracked to an specific issue)

**Comment by mgarciavaadin** [comment] 2023-08-16 17:53
Closed as investigation was completed.
It is mandatory to have an empty public constructor for the Bean used in the Grid to make it accessible to the FormFiller. So far a log message has been added when instance creation fails and an issue to look for better approaches has been created #57

**Closed by mgarciavaadin** 2023-08-16 17:53 UTC
Labels: bug
